# Run Overcommit within a Bundler context using this repo's Gemfile
gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  ScssLint:
    enabled: true
    flags: ['-c', '.scss-lint.yml']

  JsHint:
    enabled: true
    description: 'Analyze with JSHint'
    required_executable: 'jshint'
    flags: ['--verbose']
    install_command: 'npm install -g jshint'
    include: '**/*.js'

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/scss-lint'

  HardTabs:
    enabled: true

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true

# Hooks that run after HEAD changes or a file is explicitly checked out.
PostCheckout:
  ALL:
    required: false
    quiet: false

  BowerInstall:
    enabled: true
    description: 'Install bower dependencies'
    requires_files: true
    required_executable: 'bower'
    install_command: 'npm install -g bower'
    flags: ['install']
    include: 'bower.json'

  BundleInstall:
    enabled: true
    description: 'Install Bundler dependencies'
    requires_files: true
    required_executable: 'bundle'
    install_command: 'gem install bundler'
    flags: ['install']
    include:
      - 'Gemfile'
      - 'Gemfile.lock'
      - '*.gemspec'

  NpmInstall:
    enabled: true
    description: 'Install NPM dependencies'
    requires_files: true
    required_executable: 'npm'
    flags: ['install']
    include:
      - 'package.json'
